### PR TITLE
Fix cpu tick: call c func to get the _SC_CLK_TCK

### PR DESCRIPTION
**Pull request by gwind**

### CODE REVIEW

**Comment by shirou** [comment]
Thank you.  But it seems this is same as #42  and #43. And my mind is not changed. If you know how to get _SC_CLK_TCK without cgo, please let me know.

**Comment by gwind** [comment]
ok, maybe just call system command to get the cpu tick:

    getconf CLK_TCK

the getconf command is very common in most linux distribution.

**Comment by shirou** [comment]
wow! I did not know the `getconf`!

I confirmed `getconf CLK_TCK` works on Linux(Ubuntu and CentOS), FreeBSD-10.1, and OSX. I will implements this method soon. Thank you very much!

**Comment by gwind** [comment]
you are welcome, :-)

在 2015年07月16日 21:41, shirou 写道:
> wow! I did not know the |getconf|!
>
> I confirmed |getconf CLK_TCK| works on Linux(Ubuntu and CentOS),
> FreeBSD-10.1, and OSX. I will implements this method soon. Thank you
> very much!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shirou/gopsutil/pull/54#issuecomment-121958903>.
>

-- 
Li Jian ( http://ooclab.com )

**Comment by shirou** [comment]
I have implemented at 8c17a750c6e252a90c2d8afee571f2069b277e9c and 4bc631921fd78cca0a18c46042be2cb3e04b4145. Thank you so much!

**Pull request closed without merging**
