### PR TITLE
docs: fix typos and grammer

### PR DESCRIPTION
**Pull request by rasa**

### CODE REVIEW

**Review by shirou — APPROVED** [review]
Thank you so much! 

However, according to this [page](https://www.quora.com/Is-this-sentence-correct-%E2%80%9CEnglish-isn%E2%80%99t-my-tongue-language-I-apologize-for-further-mistakes%E2%80%9D), it seems "my native language" or "my mother tongue" is a commonly used. "my native tongue" is also commonly used? Sorry, I am just wondering.

**Comment by rasa** [comment]
> However, according to this [page](https://www.quora.com/Is-this-sentence-correct-%E2%80%9CEnglish-isn%E2%80%99t-my-tongue-language-I-apologize-for-further-mistakes%E2%80%9D), it seems "my native language" or "my mother tongue" is a commonly used. "my native tongue" is also commonly used? Sorry, I am just wondering.

I'm humbled that you caught that mistake, "native tongue" is definitely not correct. I've fixed it.

**Review by shirou — APPROVED** [review]
Great, thank you so much!

**Comment by rasa** [comment]
I'm glad we corrected it, but "native tongue" is used on occasion. See https://en.m.wikipedia.org/wiki/First_language .

**Comment by shirou** [comment]
I see. However, from English learner perspective, "tongue" is not a familiar word (rather than "language" at least), so "native language" is better for me.

Anyway, thank you for your kindly contribution!

**Pull request merged**
