### PR TITLE
[process] Add support for cgroups

### PR DESCRIPTION
**Pull request by atoulme**
Add support for cgroups - only on Linux, all other OSes do not expose this information.

### CODE REVIEW

**Review by astencel-sumo — APPROVED** [review]
Makes sense to me 👍

**Comment by atoulme** [comment]
@shirou wdyt?

**Comment by shirou** [comment]
I don't want to add Linux specific information anymore. However, I am thinking about [v4](https://github.com/shirou/gopsutil/discussions/1553) to have a room about this kind of information. If this implementation works well, I would like to add these information in it.

**Comment by atoulme** [comment]
I see, we will work on this separately then.

**Pull request closed without merging**
