### PR TITLE
[disk][freebsd] implement SerialNumberWithContext

### PR DESCRIPTION
**Pull request by scop**

### CODE REVIEW

**Comment by shirou** [comment]
Thank you!

From my FreeBSD 12.3 on VPS, `geom` returns `(null)` on `ident`.
```
Geom name: vtbd0
Providers:
1. Name: vtbd0
   Mediasize: 214748364800 (200G)
   Sectorsize: 512
   Mode: r2w2e3
   descr: (null)
   ident: (null)
   rotationrate: unknown
   fwsectors: 63
   fwheads: 16
```

Sorry, I don't know what kind of string geom returns other than "null", but could you add a check and return empty if at least it is `(null)` ?

**Comment by scop** [comment]
Ah, good catch. Searching the web for "geom disk list ident" gives a bunch of hits with example outputs containing serial numbers (and some `(null)`s as well).

**Comment by scop** [comment]
Not sure what to say about the codecov result, this touches FreeBSD specific code only, resulting somehow Linux coverage increasing and Windows and macOS decreasing... :thinking:

**Review by shirou — APPROVED** [review]
Thank you so much! It works perfect on my FreeBSD 12.3 machine.

**Pull request merged**
