### PR TITLE
Simplify Fix Virtualization Cache Race Condition

### PR DESCRIPTION
**Pull request by AtakanColak**
Simplifies #951

### CODE REVIEW

**Comment by Lomanic** [comment]
Thanks, I really prefer this implementation, way simpler than #951 that I disliked because it was very verbose. Could you squash your commits? Also, your git user is not always properly set in your commits (it shows on Github). And keep in mind adding `#2` in your commits creates a mention and a link to the corresponding issue. ;)

**Comment by AtakanColak** [comment]
@Lomanic thank you, I'm starting to get the hang of git. I can't seem to find a squash option though. Is it possible for you to squash merge? Also please take a look at #962

**Comment by AtakanColak** [comment]
Managed to squash using command line haha

**Comment by Lomanic** [comment]
Thanks a lot @AtakanColak, appreciated

**Pull request merged**
