### PR TITLE
Correctly detect host Procs on all platforms.

### PR DESCRIPTION
**Pull request by sean-**
Previously this only worked on Windows.  Expand to all supported platforms.

Fixes: #227

### CODE REVIEW

**Comment by shirou** [comment]
Thanks!

But unfortunately, import cycle is happened on linux. We need only number of procs, so, could you add a new function on `host/host_linux.go` such as,

```
func procs() (uint64, error) {
	f, err := os.Open(common.HostProc())
	if err != nil {
		return 0, err
	}
	list, err := f.Readdir(-1)
	f.Close()
	if err != nil {
		return 0, err
	}
	return uint64(len(list)), error
}
```

**Comment by sean-** [comment]
@shirou There you go.  LMK!

**Comment by shirou** [comment]
You implemented  `NumProcs` in the common. Really good! Thank you for your contribution!

**Comment by prologic** [comment]
Thanks!

**Pull request merged**
