### PR TITLE
Saving boot time during ProcessesWithContext call (linux).

### PR DESCRIPTION
**Pull request by bjandras**
On Linux, the system boot time is used when calculating process creation times (expressed as number of seconds since the epoch). Obtaining the boot time involves parsing the /proc/stat file, which can incur siginificant overhead on systems with many CPU cores.

Permanently caching the boot time is not an option since it can change when the system clock is updated (e.g. ntpd).

In this changeset we will save the boot time during one invocation of the ProcessesWithContext function (listing all running processes).

### CODE REVIEW

**Comment by bjandras** [comment]
This addresses issues #1070 and #1283.

To my knowledge, obtaining the boot time from /proc/stat is the only reliable
method. Alternative of subtracting the uptime from the current time is not
reliable since it requires obtaining these two times simultaneously.

**Comment by bjandras** [comment]
Simple benchmark (just calling `process.Processes()` for `testing.B.N` times:

before:
```
goos: linux
goarch: amd64
pkg: testtest
cpu: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
BenchmarkBTime-4             196           6110134 ns/op
PASS
ok      testtest        2.272s
```

with change:
```
goos: linux
goarch: amd64
pkg: testtest
cpu: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
BenchmarkBTime-4             445           2677522 ns/op
PASS
ok      testtest        1.480s
```

(depends heavily on the number of processes running)

**Review by atoulme — APPROVED** [review]

**Comment by bjandras** [comment]
Requested changes have been implemented.

**Comment by shirou** [comment]
Ah, I am sorry that I have misled you.  What I meant was that caching in context should be done by the Application that uses gopsutil, not in the gopsutil, because it is a Library. To use a different term, we are unable to accept this PR.

**Comment by bjandras** [comment]
@shirou I don't understand -- caching is done by the application, the library only uses the cached value when available.

**Comment by shirou** [comment]
We do not want to add more context values. And also, bootTime can jump if time gets adjusted, described in [this comment](https://github.com/shirou/gopsutil/issues/1070#issuecomment-842512782).

**Pull request closed without merging**
