### PR TITLE
[ios][disk] IOKit is not available on iOS

### PR DESCRIPTION
**Pull request by tmm1**
fix iOS builds with cgo trying to build with IOKit

### CODE REVIEW

**Comment by shirou** [comment]
Thank you! I don't know iOS, but [IOKit is available on iOS 16.0](https://developer.apple.com/documentation/iokit?language=objc)?

**Comment by tmm1** [comment]
You're right, they include part of IOKit on iOS now.

But the actual drive stats are still macOS only:

https://developer.apple.com/documentation/iokit/kioblockstoragedriverstatisticslatentwritetimekey/

https://github.com/shirou/gopsutil/blob/360136f40562e030fb6c558d2c15d03afe4bf970/disk/iostat_darwin.c#L96

**Comment by tmm1** [comment]
@shirou wdyt?

**Review by shirou — APPROVED** [review]
I don't have iOS devices. If it is not possible to build, I would consider this change does not break compatibility. If it breaks, someone will open an issue. so I merge this. Thank you so much!

**Pull request merged**
