### PR TITLE
Make types for OpenBSD/arm64

### LINKED ISSUE #992: Build failure on OpenBSD/aarch64
**Describe the bug**

I'm the package maintainer of Syncthing on OpenBSD. I'm seeing if I can get syncthing building on OpenBSD/aarch64. The syncthing build fails like this:
```
block$ go run build.go                                                                                                         
github.com/shirou/gopsutil/disk
# github.com/shirou/gopsutil/disk
../../go/pkg/mod/github.com/shirou/gopsutil@v3.20.10+incompatible/disk/disk_openbsd.go:81:39: undefined: sizeOfDiskstats
../../go/pkg/mod/github.com/shirou/gopsutil@v3.20.10+incompatible/disk/disk_openbsd.go:85:14: undefined: sizeOfDiskstats
../../go/pkg/mod/github.com/shirou/gopsutil@v3.20.10+incompatible/disk/disk_openbsd.go:111:34: undefined: Diskstats
../../go/pkg/mod/github.com/shirou/gopsutil@v3.20.10+incompatible/disk/disk_openbsd.go:112:9: undefined: Diskstats
exit status 2
```

I've been unable to trigger this by running `go build` in your repo, but it may be the wrong command.

**To Reproduce**

Clone syncthing master and run `go run build.go`.

**Expected behavior**

It should build :)

**Environment (please complete the following information):**

```
OpenBSD block.lan 6.8 GENERIC.MP#887 arm64
```

That's OpenBSD-current.

**Additional context**

go-1.15.2

Thanks :)

### PR DESCRIPTION
**Pull request by vext01**
As requested [here](https://github.com/shirou/gopsutil/issues/992#issuecomment-723638840).

These were generated on OpenBSD-current on a Raspberry Pi 4.

Can you tell me how to test the build and run the test suite? I don't know anything about golang!

Fixes #992

### CODE REVIEW

**Comment by Lomanic** [comment]
Thanks a lot @vext01! I should buy a Raspberry 4 one day :)

You can test your changes with `go build github.com/shirou/gopsutil/...` (checking it builds and there is no missing types) and `go test github.com/shirou/gopsutil/...` (running tests). You should also generate types for v3 modules, `cd v3 && sh ../mktypes.sh` should do it (the `mktypes.sh`script has to be fixed to handle the v3 modules, I'm working on that).

**Comment by vext01** [comment]
OK, I've added a commit for the v3 types, but it doesn't appear to build.

In fact, I'm unsure if I'm doing this right. The struggles of someone who's never used golang 🆘 

```
$ go build github.com/shirou/gopsutil/...                                                            
internal/common/common_openbsd.go:11:2: cannot find package "golang.org/x/sys/unix" in any of:      
        /usr/local/go/src/golang.org/x/sys/unix (from $GOROOT)                                      
        /home/edd/go/src/golang.org/x/sys/unix (from $GOPATH)         
```

So I guess we need to use `go get`?

```                                                                                                                                                                  
$ go get github.com/shirou/gopsutil/...                                                              
# golang.org/x/sys/unix                                                                                                                                                                                             
SIGILL: illegal instruction                                                                               
PC=0x1aa194 m=2 sigcode=1                            
instruction bytes: 0x1b 0x28 0x85 0x52 0x3f 0x0 0x1b 0x6b 0xec 0x1 0x0 0x54 0x0 0x3c 0x40 0xd3

goroutine 36 [running]:                              
cmd/internal/obj/arm64.(*ctxt7).opldr12(0x4001199d30, 0x40001844c0, 0x2941, 0x50)
        /usr/local/go/src/cmd/internal/obj/arm64/asm7.go:6302 +0x184 fp=0x4001199840 sp=0x40011997f0 pc=0x1aa194
cmd/internal/obj/arm64.(*ctxt7).asmout(0x4001199d30, 0x40001844c0, 0xb90ef8, 0x4001199c88, 0x6, 0x6)
        /usr/local/go/src/cmd/internal/obj/arm64/asm7.go:3352 +0xa8d8 fp=0x4001199bc0 sp=0x4001199840 pc=0x1a5ae8
... loads more stacktrace
```

But it seems to be enough to run the build now:
```
$ go build github.com/shirou/gopsutil/...     
# github.com/shirou/gopsutil/disk
disk/disk_openbsd.go:90:36: cannot use d.Name[:] (type []uint8) as type []int8 in argument to common.IntToString
# github.com/shirou/gopsutil/v3/disk
v3/disk/disk_openbsd.go:90:36: cannot use d.Name[:] (type []uint8) as type []int8 in argument to common.IntToString
# github.com/shirou/gopsutil/v3/process
v3/process/process_openbsd.go:49:35: cannot use k.Comm[:] (type []uint8) as type []int8 in argument to common.IntToString
v3/process/process_openbsd.go:244:19: undefined: mem.GetpageSizeWithContext
# github.com/shirou/gopsutil/process
process/process_openbsd.go:49:35: cannot use k.Comm[:] (type []uint8) as type []int8 in argument to common.IntToString
```

**Comment by Lomanic** [comment]
There's a type mismatch in the code generated by mktypes.sh, it doesn't build currently. I don't understand why yet, it looks like it's the `char` conversion that changed from int8 to uint8 (compare with the amd64 files). I should download a newer openbsd version than 6.5 to check that.

**Comment by vext01** [comment]
It rings a bell that the sightedness of a char varies between platforms.

**Comment by vext01** [comment]
Yes, [here](https://www.linuxtopia.org/online_books/an_introduction_to_gcc/gccintro_71.html):
> The C and C++ standards allows the character type char to be signed or unsigned, depending on the platform and compiler. Most systems, including x86 GNU/Linux and Microsoft Windows, use signed char, but those based on PowerPC and ARM processors typically use unsigned char.

I don't know if the same semantics are expected of go?

**Comment by Lomanic** [comment]
We generate some types from their C definition, so we inherit hat indeed, thanks for the pointer. We could just blindly cast the slices to uint8 like in the following diff

```diff
diff --git a/disk/disk_openbsd.go b/disk/disk_openbsd.go
index e675580..f71862f 100644
--- a/disk/disk_openbsd.go
+++ b/disk/disk_openbsd.go
@@ -87,7 +87,11 @@ func IOCountersWithContext(ctx context.Context, names ...string) (map[string]IOC
 		if err != nil {
 			continue
 		}
-		name := common.IntToString(d.Name[:])
+		uint8Name := make([]uint8, len(d.Name))
+		for i, v := range d.Name {
+			uint8Name[i] = uint8(v)
+		}
+		name := common.UintToString(uint8Name)
 
 		if len(names) > 0 && !common.StringsHas(names, name) {
 			continue
diff --git a/process/process_openbsd.go b/process/process_openbsd.go
index 0404b4b..c439d92 100644
--- a/process/process_openbsd.go
+++ b/process/process_openbsd.go
@@ -46,7 +46,11 @@ func (p *Process) NameWithContext(ctx context.Context) (string, error) {
 	if err != nil {
 		return "", err
 	}
-	name := common.IntToString(k.Comm[:])
+	uint8Name := make([]uint8, len(k.Comm))
+	for i, v := range d.Name {
+		uint8Name[i] = uint8(v)
+	}
+	name := common.UintToString(uint8Name)
 
 	if len(name) >= 15 {
 		cmdlineSlice, err := p.CmdlineSliceWithContext(ctx)
diff --git a/v3/disk/disk_openbsd.go b/v3/disk/disk_openbsd.go
index 24324a4..7530901 100644
--- a/v3/disk/disk_openbsd.go
+++ b/v3/disk/disk_openbsd.go
@@ -87,7 +87,11 @@ func IOCountersWithContext(ctx context.Context, names ...string) (map[string]IOC
 		if err != nil {
 			continue
 		}
-		name := common.IntToString(d.Name[:])
+		uint8Name := make([]uint8, len(d.Name))
+		for i, v := range d.Name {
+			uint8Name[i] = uint8(v)
+		}
+		name := common.UintToString(uint8Name)
 
 		if len(names) > 0 && !common.StringsHas(names, name) {
 			continue
diff --git a/v3/process/process_openbsd.go b/v3/process/process_openbsd.go
index 7325f09..1b29204 100644
--- a/v3/process/process_openbsd.go
+++ b/v3/process/process_openbsd.go
@@ -46,7 +46,11 @@ func (p *Process) NameWithContext(ctx context.Context) (string, error) {
 	if err != nil {
 		return "", err
 	}
-	name := common.IntToString(k.Comm[:])
+	uint8Name := make([]uint8, len(k.Comm))
+	for i, v := range d.Name {
+		uint8Name[i] = uint8(v)
+	}
+	name := common.UintToString(uint8Name)
 
 	if len(name) >= 15 {
 		cmdlineSlice, err := p.CmdlineSliceWithContext(ctx)
```

At least it compiles from what I see now. Would test with these changes applied with the same commands as in https://github.com/shirou/gopsutil/pull/993#issuecomment-724240064 on your arm64 host on openbsd?

**Comment by Lomanic** [comment]
I guess you also need the following diff for the tests to runbut it's unrelated to your PR itself

```diff
diff --git a/v3/process/process_openbsd.go b/v3/process/process_openbsd.go
index 6e45d84..7325f09 100644
--- a/v3/process/process_openbsd.go
+++ b/v3/process/process_openbsd.go
@@ -241,7 +241,7 @@ func (p *Process) MemoryInfoWithContext(ctx context.Context) (*MemoryInfoStat, e
 	if err != nil {
 		return nil, err
 	}
-	pageSize, err := mem.GetpageSizeWithContext(ctx)
+	pageSize, err := mem.GetPageSizeWithContext(ctx)
 	if err != nil {
 		return nil, err
 	}
```

**Comment by vext01** [comment]
Hi @Lomanic 

It seems the patch doesn't apply:
```
$ patch -CEsp1 < patch1.diff  
1 out of 1 hunks failed
1 out of 1 hunks failed
1 out of 1 hunks failed
1 out of 1 hunks failed
```

**Comment by Lomanic** [comment]
This patch applies with `git apply` (`git apply <patch1.diff`). Otherwise, it's only a matter of search and replace.

The second patch is not needed anymore if you rebase from master (`git pull --rebase origin master` with `origin` as upstream remote).

**Comment by Lomanic** [comment]
Hi @vext01, will you be able to test the changes in https://github.com/shirou/gopsutil/pull/993#issuecomment-727621843 (`git apply` or search & replace)?

**Comment by vext01** [comment]
Before and after a rebase, I get:
```
$ git apply patch.diff
error: patch failed: disk/disk_openbsd.go:87
error: disk/disk_openbsd.go: patch does not apply
error: patch failed: process/process_openbsd.go:46
error: process/process_openbsd.go: patch does not apply
error: patch failed: v3/disk/disk_openbsd.go:87
error: v3/disk/disk_openbsd.go: patch does not apply
error: patch failed: v3/process/process_openbsd.go:46
error: v3/process/process_openbsd.go: patch does not apply
```

Can you make a branch containing the changes you'd like tested and I'll try that?

**Comment by Lomanic** [comment]
There you go https://github.com/Lomanic/gopsutil/tree/openbsd-arm64 (with your commits squashed and rebased from upstream master).

(It could have even been simpler to [enable "repository maintainer permissions on existing pull requests"](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests), never used this function yet)

**Comment by vext01** [comment]
Thanks.

I cloned your repo to `~/go/src/github.com/Lomanic/gopsutil`, changed to your branch, and ran `go test github.com/Lomanic/gopsutil/...`. This is the output:

```
package github.com/Lomanic/gopsutil/cpu
        cpu/cpu.go:13:2: use of internal package github.com/shirou/gopsutil/internal/common not allowed
package github.com/Lomanic/gopsutil/disk
        disk/disk.go:7:2: use of internal package github.com/shirou/gopsutil/internal/common not allowed
package github.com/Lomanic/gopsutil/docker
        docker/docker.go:8:2: use of internal package github.com/shirou/gopsutil/internal/common not allowed
package github.com/Lomanic/gopsutil/host
        host/host.go:10:2: use of internal package github.com/shirou/gopsutil/internal/common not allowed
package github.com/Lomanic/gopsutil/load
        load/load.go:6:2: use of internal package github.com/shirou/gopsutil/internal/common not allowed
package github.com/Lomanic/gopsutil/mem
        mem/mem.go:6:2: use of internal package github.com/shirou/gopsutil/internal/common not allowed
package github.com/Lomanic/gopsutil/net
        net/net.go:8:2: use of internal package github.com/shirou/gopsutil/internal/common not allowed
package github.com/Lomanic/gopsutil/process
        process/process.go:14:2: use of internal package github.com/shirou/gopsutil/internal/common not allowed
package github.com/Lomanic/gopsutil/v3/cpu
        v3/cpu/cpu.go:13:2: use of internal package github.com/shirou/gopsutil/v3/internal/common not allowed
package github.com/Lomanic/gopsutil/v3/disk
        v3/disk/disk.go:7:2: use of internal package github.com/shirou/gopsutil/v3/internal/common not allowed
package github.com/Lomanic/gopsutil/v3/docker
        v3/docker/docker.go:8:2: use of internal package github.com/shirou/gopsutil/v3/internal/common not allowed
package github.com/Lomanic/gopsutil/v3/host
        v3/host/host.go:10:2: use of internal package github.com/shirou/gopsutil/v3/internal/common not allowed
package github.com/Lomanic/gopsutil/v3/load
        v3/load/load.go:6:2: use of internal package github.com/shirou/gopsutil/v3/internal/common not allowed
package github.com/Lomanic/gopsutil/v3/mem
        v3/mem/mem.go:6:2: use of internal package github.com/shirou/gopsutil/v3/internal/common not allowed
package github.com/Lomanic/gopsutil/v3/net
        v3/net/net.go:8:2: use of internal package github.com/shirou/gopsutil/v3/internal/common not allowed
package github.com/Lomanic/gopsutil/v3/process
        v3/process/process.go:14:2: use of internal package github.com/shirou/gopsutil/v3/internal/common not allowed
```

And it exits `1`, so I guess something isn't right?

I also tried just `go test ...` in the source dir and saw similar errors.

**Comment by Lomanic** [comment]
> I cloned your repo to ~/go/src/github.com/Lomanic/gopsutil

You should have cloned it to `~/go/src/github.com/shirou/gopsutil`, or if you already have gopsutil cloned there, add a remote with `git remote add lomanic https://github.com/Lomanic/gopsutil` and `git fetch --all && git checkout lomanic/openbsd-arm64`

**Comment by vext01** [comment]
Oops. My apologies. I really know nothing about the golang.

So, I think this is right:
```
$ pwd           
/home/edd/go/src/github.com/shirou/gopsutil
$ git remote -v 
origin  https://github.com/Lomanic/gopsutil (fetch)
origin  https://github.com/Lomanic/gopsutil (push)
$ PAGER= git branch
  master
* openbsd-arm64
$ git rev-parse HEAD
ec167b729e855a228821d553971684deb3d10459
```

Here's the output of the test (I had to `go get github.com/stretchr/testify` first because it was complaining it couldn't find it):
```
$ $ go test github.com/shirou/gopsutil/...
?   	github.com/shirou/gopsutil	[no test files]
--- FAIL: TestCpu_times (0.00s)
    cpu_test.go:62: {"cpu":"cpu-total","user":22.6,"system":0.0,"idle":0.0,"nice":0.0,"iowait":0.0,"irq":16.5,"softirq":0.0,"steal":0.0,"guest":0.0,"guestNice":0.0}
    cpu_test.go:68: 
        	Error Trace:	cpu_test.go:68
        	Error:      	Relative error is too high: 2 (expected)
        	            	        < 3.0008861320336724 (actual)
        	Test:       	TestCpu_times
--- FAIL: TestCpuInfo (0.00s)
    cpu_test.go:117: error operation not supported
    cpu_test.go:120: could not get CPU Info
FAIL
FAIL	github.com/shirou/gopsutil/cpu	0.306s
ok  	github.com/shirou/gopsutil/disk	(cached)
?   	github.com/shirou/gopsutil/docker	[no test files]
# github.com/shirou/gopsutil/process
process/process_openbsd.go:50:20: undefined: d
FAIL	github.com/shirou/gopsutil/host [build failed]
ok  	github.com/shirou/gopsutil/internal/common	(cached)
ok  	github.com/shirou/gopsutil/load	(cached)
ok  	github.com/shirou/gopsutil/mem	(cached)
ok  	github.com/shirou/gopsutil/net	(cached)
# github.com/shirou/gopsutil/process [github.com/shirou/gopsutil/process.test]
process/process_openbsd.go:50:20: undefined: d
FAIL	github.com/shirou/gopsutil/process [build failed]
--- FAIL: TestCpu_times (0.00s)
    cpu_test.go:62: {"cpu":"cpu-total","user":23.0,"system":0.0,"idle":0.0,"nice":0.0,"iowait":0.0,"irq":17.0,"softirq":0.0,"steal":0.0,"guest":0.0,"guestNice":0.0}
    cpu_test.go:68: 
        	Error Trace:	cpu_test.go:68
        	Error:      	Relative error is too high: 2 (expected)
        	            	        < 3.0008684324793737 (actual)
        	Test:       	TestCpu_times
--- FAIL: TestCpuInfo (0.00s)
    cpu_test.go:117: error operation not supported
    cpu_test.go:120: could not get CPU Info
FAIL
FAIL	github.com/shirou/gopsutil/v3/cpu	0.377s
ok  	github.com/shirou/gopsutil/v3/disk	(cached)
ok  	github.com/shirou/gopsutil/v3/docker	(cached)
# github.com/shirou/gopsutil/v3/process
v3/process/process_openbsd.go:50:20: undefined: d
FAIL	github.com/shirou/gopsutil/v3/host [build failed]
ok  	github.com/shirou/gopsutil/v3/internal/common	(cached)
ok  	github.com/shirou/gopsutil/v3/load	(cached)
ok  	github.com/shirou/gopsutil/v3/mem	(cached)
ok  	github.com/shirou/gopsutil/v3/net	(cached)
# github.com/shirou/gopsutil/v3/process [github.com/shirou/gopsutil/v3/process.test]
v3/process/process_openbsd.go:50:20: undefined: d
FAIL	github.com/shirou/gopsutil/v3/process [build failed]
FAIL
```

Looks like we are getting somewhere.

**Comment by Lomanic** [comment]
Well, this looks quite promising in fact, thanks for testing this. The failing tests are unrelated to the changes, these tests should be improved as they are also often failing on Github Actions. Would you force-push ec167b729e855a228821d553971684deb3d10459 to your branch @vext01 then?

**Comment by vext01** [comment]
Done! Sorry for the delay!

**Comment by vext01** [comment]
Let's not forget this one.

**Comment by Lomanic** [comment]
Hi, thanks for the reminder, I overlooked it in my last message in fact, as I didn't see the following error
```
process/process_openbsd.go:50:20: undefined: d
FAIL	github.com/shirou/gopsutil/host [build failed]
```
I did a silly copy-paste mistake it seems (from the disk package I can see now), I updated my branch at https://github.com/Lomanic/gopsutil/tree/openbsd-arm64 (I'm not sure I can push to your branch) and I could test it on my old OpenBSD 6.5 i386 VM this time, without issues ; the process package now builds and has its tests run successfully.

If you can confirm me that tests run successfully on your arm64 host also (minus the TestCpu_times failing test, it's unrelated), it looks like we will finally be able to merge this. Thanks for staying for so long over here, appreciated.

**Comment by tobias-hildebrandt** [comment]
Hello, I'm running OpenBSD -current on my Raspberry Pi 4 (2GB RAM version).
I hope I am able to help with my machine's test results.

I've run `go test ./...` on Lomanic's `openbsd-arm64` branch and I've attached a [log](https://github.com/shirou/gopsutil/files/6087158/gopsutil-test1.txt).
I've also attached the output of my [`go env`](https://github.com/shirou/gopsutil/files/6087048/goenv.txt).
The output of my `uname -a` is `OpenBSD rpi4-openbsd.none 6.9 GENERIC.MP#1051 arm64`.
I am also pretty clueless about Go, so let me know if there is anything else I should run.

**Comment by Lomanic** [comment]
superseded by #1052

**Pull request closed without merging**
