### PR TITLE
[OpenBSD][CPU] fix per-cpu

### PR DESCRIPTION
**Pull request by omar-polo**
#646 related

While there, rearrange the last if statement to make it more similar to the other two.

### CODE REVIEW

**Comment by omar-polo** [comment]
I've pushed a fix for the first issue, the one regarding `cpu.Info()`. I haven't been able to find out why, but `unix.Sysctl("hw.ncpuonline")` fails on:
 - 6.3 on i386
 - 6.4 on amd64
 - CURRENT on amd64

As a workaround, use `unix.Syscall6`. Tested on amd64 (6.4 and CURRENT)

**Comment by Lomanic** [comment]
Thanks for the `cpu.Info` fix, I was working on exactly the same fix this morning. I can confirm it works in OpenBSD 6.4 amd64.

I don't have a multi-core physical machine with OpenBSD (my Virtualbox VM doesn't seem to see more than one core after adding more in Virtualbox machine configuration) to test atm, but this looks OK to me.

**Comment by omar-polo** [comment]
I've managed to fix also the other issue I mentioned on #646 

The reason I got that strange percentage I reported is because of `hw.smt`: `runtime.NumCPU()` returns 4 on my system, but `hw.ncpus` is 8. Only `cpu{0,2,4,6}` are effectively used by the scheduler, but the loop was asking only for `cpu{0..3}`. The last commit is an attempt to detect `hw.smt` and act accordingly. Tested on yesterday' snapshot on amd64.

----

@Lomanic thanks for reviewing the other commits. I'm sorry, I know nothing about running OpenBSD on virtualbox, so I cannot help there :/

**Comment by omar-polo** [comment]
fixed a typo: I forgot to pass the address of the variable instead of the variable itself.

I've tested on the latest snapshot on amd64 with `hw.smt` both enabled and disabled and the results are correct.

**Comment by omar-polo** [comment]
Hi!

I've tested these changes on i386 and noticed that:
 - `hw.ncpuonline` is "operation not supported" on OpenBSD 6.3 (it was added with 6.4 IIRC). Since 6.3 is going EOL soon I don't think it's an issue;
 - if `hw.smt` is not present (ie on i386) the sysctl returns `EOPNOTSUPP`. I've pushed a commit to handle that case;
 - `cpuTimes` is a `[]int64`: on i386 `binary.Read` returns `ErrUnexpectedEOF`. I don't know how to handle this case (binary.Read won't accept an int slice).

Except for this last issue, I think this pr is finished :)

**Comment by shirou** [comment]
OpenBSD released every six months and only support latest two releases.
http://www.openbsd.org/faq/faq5.html#Flavors

So 6.3 will be EOL as you said, but not yet. I don't want remove supported release, so after [6.5 released](https://www.openbsd.org/65.html), I will merge this PR. thank you for you contribution.

**Comment by Lomanic** [comment]
OpenBSD 6.5 got released https://marc.info/?l=openbsd-announce&m=155611207805565&w=2

Does it mean 6.3 is now EOL?

> cpuTimes is a []int64: on i386 binary.Read returns ErrUnexpectedEOF. I don't know how to handle this case (binary.Read won't accept an int slice).

This is problematic and should be fixed before accepting this PR. Instead of doing manual syscalls, wouldn't it be possible (and would it fix it on i386) to use `common.SysctlUint` instead?

**Comment by omar-polo** [comment]
Sorry for the delay.

> OpenBSD 6.5 got released https://marc.info/?l=openbsd-announce&m=155611207805565&w=2
> 
> Does it mean 6.3 is now EOL?

Yup, they support only the two most recent OpenBSD releases (that is, only
the last two release get security fixes [1].)

> > cpuTimes is a []int64: on i386 binary.Read returns ErrUnexpectedEOF. I don't know how to handle this case (binary.Read won't accept an int slice).
> 
> This is problematic and should be fixed before accepting this PR. Instead of doing manual syscalls, wouldn't it be possible (and would it fix it on i386) to use `common.SysctlUint` instead?

Luckily I've just finished updating a i386 from 6.3 to 6.5. I'll try to fix that
and test on both amd64 and i386.

Thanks for the suggestion of `common.SysctlUint`, I think I've missed it.

--

[1]: https://www.openbsd.org/faq/faq5.html#Flavors

**Comment by omar-polo** [comment]
I've recalled why I didn't used `unix.SysctlUint32`: on OpenBSD hw.ncpuonline does not work:

```
import (
        "fmt"
        "golang.org/x/sys/unix"
)

func main() {
        fmt.Println(unix.SysctlUint32("hw.ncpuonline"))
        // outputs: "0 invalid argument"
}
```

Anyway, I've just tried the code on amd64 and i386 (both running 6.5-STABLE) and everything works. As I've been told, OpenBSD uses 32bit integers for both archs, so the error I got was probably due to something not working with 6.3.

I still have to try on 6.4.

**Comment by omar-polo** [comment]
Tested on 6.4-STABLE on i386 (emulated under qemu, it's slow...) and it works.

Tested on 6.4-STABLE on amd64 (under qemu) and it works.

So, the `ErrUnexpectedEOF` I got was probably due to something 6.3 specific that I haven't tracked down.

**Comment by Lomanic** [comment]
> Thanks for the suggestion of `common.SysctlUint`, I think I've missed it. 

It's only declared for freebsd, that's probably why you missed it 😉. Setting it in `internal/common/common_openbsd.go` and calling it with `common.SysctlUint("hw.ncpuonline")` I had the same `invalid argument` error unfortunately (only tested on OpenBSD 6.4 amd64).

Thanks for testing on different archs and versions, I will check also. When it's merged, if we have reports of users under 6.3, we might perhaps implement a workaround for `hw.ncpuonline` by calling `sysctl -n` if the syscall fails.

**Comment by omar-polo** [comment]
ping :)

**Comment by shirou** [comment]
Thank you reporting about OpenBSD 6.3 has some issue, but as you said, 6.3 is now EOL. So I merge this PR. If anyone meet this issue on OpenBSD 6.3, please open a new ticket or PR.

Thank you for your contribution!

**Pull request merged**
