### PR TITLE
move common package to public from internal.

### PR DESCRIPTION
**Pull request by shirou**
This PR move `internal/common` to top `common` package, outside of `internal`. So users can use common package contents. 

related: #665 

----
After several years passed after `internal` is introduced in Go, I personally think library does not need to use this feature, especially OSS package. There are many users and many kind of demands. `internal` prevents their use case.

### CODE REVIEW

**Comment by Lomanic** [comment]
I'm glad that you bring this up.
I understand your concern, but it removes even more flexibility for us maintainers. We are already really blocked for API breaking changes, we would be even more constrained if we make this part of the library public. As I was saying in https://github.com/shirou/gopsutil/issues/580#issuecomment-420180804, there are solutions for developers wanting to use internal functions in their own work. 

But I would agree with this PR if we had more flexibility for API breaking changes, we could assume downstream users vendor gopsutil or use modules, that both pin their version of gopsutil.

**Comment by marcv81** [comment]
This PR was started because there is no external common package, and we would like to add a custom error type shared across all gopsutil packages. Maybe we could instead create a new common package for that is not internal?

**Comment by Lomanic** [comment]
That's indeed an option. For me this is also the occasion to talk about the huge limitation we imposed ourselves of not breaking public APIs between non-major versions. I think this is paralyzing development of the library.

**Comment by danielnelson** [comment]
I think you won't want to make breaking changes between non-major version changes, it breaks with the semantic versioning scheme which is now integral to versioning in Go.  I also think if you break compatibility too frequently you will just end up with many projects using an out-of-date version.

That said, there is some sweet spot to be found and v2 came out years ago.  Maybe it's worth working on a v3 with context support across the board and better error reporting methods?

**Comment by shirou** [comment]
So, there are some options.

1. Move internal common to public.
2. Create `hosts.Warning`.
3. Create `common` package other than current internal.
4. Any other good error reporting and will introduce on v3.

I can understand @Lomanic concern. So, I will close this issue and take option 2. However, if we can found something on option 4, I will create v3 (finally). Let's discuss on another issue.

**Comment by shirou** [comment]
and also an option.

5. any other good solution without breaking API

**Comment by Lomanic** [comment]
Maybe we could make public the `common` package but make it clear (in documentation) that its API is not stable. While still keeping the rest of the library stable API-wise between non-major versions?

**Comment by shirou** [comment]
I will create another PR which creates `general` package on the top directory and listen opinions. Thank you for joining discussion.

**Pull request closed without merging**
