### PR TITLE
get tests passing on s390x

### PR DESCRIPTION
**Pull request by jeffweiss**
This should address the test errors reported in #990

### CODE REVIEW

**Review by shirou — APPROVED** [review]
I don't have a s390x so I can not confirm it works or not. However this PR seems does not break compatibility on other platform. So I merge this. Thank you for your great contribution!

**Comment by Nayana-ibm** [comment]
@shirou I can verify on s390x. Please let me know the steps to build/test.

**Comment by Nayana-ibm** [comment]
I verified using steps mentioned in Github Actions build_test
All tests passing on s390x.

```
go: downloading github.com/tklauser/go-sysconf v0.3.11
go: downloading github.com/stretchr/testify v1.8.4
go: downloading golang.org/x/sys v0.9.0
go: downloading github.com/tklauser/numcpus v0.6.0
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading gopkg.in/yaml.v3 v3.0.1
?       github.com/shirou/gopsutil/v3   [no test files]
?       github.com/shirou/gopsutil/v3/common    [no test files]
ok      github.com/shirou/gopsutil/v3/cpu       0.202s
ok      github.com/shirou/gopsutil/v3/disk      0.020s
ok      github.com/shirou/gopsutil/v3/docker    0.164s
ok      github.com/shirou/gopsutil/v3/host      0.023s
ok      github.com/shirou/gopsutil/v3/internal/common   0.064s
ok      github.com/shirou/gopsutil/v3/load      0.022s
ok      github.com/shirou/gopsutil/v3/mem       0.009s
ok      github.com/shirou/gopsutil/v3/net       0.017s
ok      github.com/shirou/gopsutil/v3/process   2.266s

```

**Comment by shirou** [comment]
Great! Thank you for your work!

**Pull request merged**
