### PR TITLE
Add disk.IOCountersForNames function

### PR DESCRIPTION
**Pull request by danielnelson**
Operates like disk.IOCounters, but accepts an array of names to limit the results.

I only tested this on linux.

Should address #341

### CODE REVIEW

**Comment by danielnelson** [comment]
I'll setup a branch of Telegraf tomorrow and we can use it to make sure this improves the performance on systems with many disks.

**Comment by danielnelson** [comment]
@beheerderdag Can you try out [this build](https://6537-33258973-gh.circle-artifacts.com/0/tmp/circle-artifacts.jLmkSPt/telegraf.gz) on your system which uses the introduced functions?

**Comment by beheerderdag** [comment]
Thanks for this. Yes, it seems to be behaving ok. 

```

root# ./telegraf.fix version
Telegraf v1.2.0-rc1-124-g4425235 (git: diskio-names 4425235)

root# time telegraf.fix -config /etc/telegraf/telegraf.conf -input-filter diskio -test
* Plugin: inputs.diskio, Collection 1
> diskio,name=sda,host=dmf writes=8658237i,read_time=22333256i,io_time=106042656i,reads=1729290i,read_bytes=103658150400i,write_bytes=240348573696i,write_time=566561988i,iops_in_progress=0i 1491817752000000000
> diskio,name=sdb,host=dmf writes=35678i,read_bytes=3509836288i,read_time=9349424i,write_time=7089736i,iops_in_progress=0i,reads=1576950i,io_time=9374672i,write_bytes=84229632i 1491817752000000000

real    0m0.419s
user    0m0.052s
sys     0m0.372s

```

**Comment by shirou** [comment]
Thank you everyone!

**Comment by phemmer** [comment]
Too little too late, but since this hasn't made it into an official release yet, what about just making `disk.IOCounters()` a variadic? That would preserve compatability without having to introduce `disk.IOCountersForNames()`.

**Comment by danielnelson** [comment]
@shirou This is a pretty good idea, I could do this if you like.

**Comment by shirou** [comment]
@phemmer oh, I think it would great! 
@danielnelson Do you mind making a PR?
Thank you!

**Comment by danielnelson** [comment]
#351

**Pull request merged**
