### PR TITLE
Read windows platform name, version, and family from systeminfo command

### PR DESCRIPTION
**Pull request by cbednarski**

### CODE REVIEW

**Comment by shirou** [comment]
Thank you for the PR. However, the other PR #60 has same functionality which can get name, version, and family from `WMI.Win32_OperatingSystem`.

Your approach use `systeminfo`. Since I am not familiar with Windows, I don't know which is better way. Could you give me some differences?

**Comment by cbednarski** [comment]
Hi! I noticed that as I was submitting this PR. I don't know what is different between these two approaches.

Here is the output from `systeminfo` on my Windows 10 dev VM. I think this command can also provide Virtualization info (see last line) but it does not display currently.

```

Host Name:                 DESKTOP-T1QKJR
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.10240 N/A Build 10240
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          vagrant
Registered Organization:
Product ID:                00330-80000-00000-AA657
Original Install Date:     8/19/2015, 2:00:11 PM
System Boot Time:          8/27/2015, 4:04:47 PM
System Manufacturer:       VMware, Inc.
System Model:              VMware Virtual Platform
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 58 Stepping 9 GenuineIntel ~2693 Mhz
BIOS Version:              Phoenix Technologies LTD 6.00, 7/2/2015
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-08:00) Pacific Time (US & Canada)
Total Physical Memory:     4,095 MB
Available Physical Memory: 2,446 MB
Virtual Memory: Max Size:  4,799 MB
Virtual Memory: Available: 3,191 MB
Virtual Memory: In Use:    1,608 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-T1QKJR
Hotfix(s):                 7 Hotfix(s) Installed.
                           [01]: KB3074678
                           [02]: KB3074686
                           [03]: KB3081441
                           [04]: KB3081444
                           [05]: KB3081449
                           [06]: KB3081452
                           [07]: KB3087916
Network Card(s):           2 NIC(s) Installed.
                           [01]: Intel(R) 82574L Gigabit Network Connection
                                 Connection Name: Ethernet0
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.1.1
                                 IP address(es)
                                 [01]: 192.168.1.67
                                 [02]: fe80::61df:c3cc:ba03:1302
                           [02]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.
```

**Comment by cbednarski** [comment]
Personally I am OK with either approach, so long as I can get the OS Name and OS Version.

**Comment by cbednarski** [comment]
I am using this script to test: https://github.com/cbednarski/sysinfo. The output from both pull-requests is nearly the same:

From #60:
```
C:\Users\vagrant\go\src\github.com\shirou\gopsutil [mayowapr +1 ~0 -0 !]> go run systest.go

----Host Info ----

2015/08/27 19:07:40 [DEBUG] &host.HostInfoStat{Hostname:"DESKTOP-...", Uptime:0x2adc, Procs:0x3e, OS:"windows", Platform:"Microsoft Windows 10 Pro", PlatformFamily:"Desktop OS", PlatformVersion:"10.0.10240", VirtualizationSystem:"", VirtualizationRole:""}

hostInfo.Hostname        DESKTOP-...
hostInfo.OS              windows
hostInfo.Platform        Microsoft Windows 10 Pro
hostInfo.PlatformVersion 10.0.10240
hostInfo.PlatformFamily  Desktop OS
```

From #65:
```
C:\Users\vagrant\go\src\github.com\shirou\gopsutil [f-windows-platform +1 ~0 -0 !]> go run systest.go

----Host Info ----

2015/08/27 19:07:48 [DEBUG] &host.HostInfoStat{Hostname:"DESKTOP-...", Uptime:0x2ae5, Procs:0x3e, OS:"", Platform:"Microsoft Windows 10 Pro\r", PlatformFamily:"Standalone Workstation\r", PlatformVersion:"10.0.10240 N/A Build 10240\r", VirtualizationSystem:"", VirtualizationRole:""}

hostInfo.Hostname        DESKTOP-...
hostInfo.OS
hostInfo.Platform        Microsoft Windows 10 Pro
hostInfo.PlatformVersion 10.0.10240 N/A Build 10240
hostInfo.PlatformFamily  Standalone Workstation
```

However, the wim implementation in #65 is quite a bit faster. I'm going to close this PR in favor of the wim implementation. There are some bugs in the other PR so I may fork #60 to only make the wim changes and resubmit.

**Pull request closed without merging**
