### PR TITLE
get docker container cpu usage from cpuacct.usage

### PR DESCRIPTION
**Pull request by CMGS**
This PR for:

* Get cgroup cpu usage from cpuacct.usage, it's a nanoseconds data, so I trans it to seconds.
* Make ```CgroupCPUWithContext``` return same unit like ```cpu.Times```. I saw cpu.Times will trans jiffies to seconds, so here should divide ```CPUTick```.

After this change, we can calculate container CPU percent in host view and container view like this:

```
interval := Seconds
containerCPUStat1 := CgroupCPUDocker(cid)
hostCPUStat1 := cpu.Times(false)[0]
time.sleep(interval)
hostCPUStat2 := cpu.Times(false)[0]
containerCPUStat2 := CgroupCPUDocker(cid)

percentInHostView := (containerCPUStat2.Usage - containerCPUStat1.Usage) / (hostCPUStat2.Total() - hostCPUStat1.Total())

percentInContainerView := percentInHostView * CPUNumbers
```

### CODE REVIEW

**Comment by shirou** [comment]
Thank you for your PR. but it seems this PR breaks compatibility about `CgroupCPU`. (`*cpu.TimesStat` -> `CgroupCPUStat`) We don't want to change API compatiblity, so it should be merge on v3.

or, because `CgroupCPUUsage` is just added and not break compatibility, we can merge it if you separate this PR.

**Comment by CMGS** [comment]
@shirou So, could I add Usage into cpu.TimesStat? In this way, ```CgroupCPU``` can return ```*cpu.TimesStat```

**Comment by shirou** [comment]
No. `cpuacct`. If you add only `CgroupCPUUsage` users who use cgroup can get usage without breaking. compatibility. No need to add usage to `CgroupCPU`, I think.

**Comment by CMGS** [comment]
OK, let me think about it...

**Comment by shirou** [comment]
Sorry for late response and thank you for your contribution!

**Pull request merged**
