### PR TITLE
add android support for host

### PR DESCRIPTION
**Pull request by ilyaiqoqo**

### CODE REVIEW

**Comment by shirou** [comment]
I have not checked it can work or not, but it looks good. Thank you!

**Comment by Lomanic** [comment]
A lot of issues with this PR which shouldn't have been merged, started a review but didn't submit it in time. Submitting it now with my remarks.

**Comment by shirou** [comment]
ugah sorry and thank you!

**Comment by shirou** [comment]
sorry and thank you @Lomanic. I will open a revert PR.

**Pull request merged**
