### PR TITLE
Fix for track disk stats when running in container

### PR DESCRIPTION
**Pull request by i-prudnikov**
The commented block has 2 problems, so should be disabled:
1. Will not work, in case we track disk info on the host from container, as /dev will be mapped into other mount point
2. Useful info about vg name removed if we follow symlink, here the example:
```
~# ls -la /dev/mapper/dm--01--vg-root
lrwxrwxrwx 1 root root 7 Oct  3 10:47 /dev/mapper/dm--01--vg-root -> ../dm-0
```
Issue is opened:
https://github.com/shirou/gopsutil/issues/817

### CODE REVIEW

**Comment by shirou** [comment]
related #686

Thanks for the issue! your are right. we should add `HOST_MOUNT_PREFIX` to every device mounted path. 

so could you change to add `common.GetEnv("HOST_MOUNT_PREFIX"` as you suggested, instead of deleting ?

```
devpath, err := filepath.EvalSymlinks(common.GetEnv("HOST_MOUNT_PREFIX","/",d.Device))
```

**Comment by Lomanic** [comment]
What about a `HOST_DEV` mapping `/dev` variable like the other ones?

**Comment by i-prudnikov** [comment]
Implemented with HOST_DEV

**Comment by shirou** [comment]
It looks nice for me! Thank you for your contribution!

(I will add `HOST_DEV` to README)

**Pull request merged**
