### PR TITLE
fixed "cannot use stat.Mntfromname[:] (type []byte) as type []int8 in…

### PR DESCRIPTION
**Pull request by chrisamti**
… argument to common.IntToString" on darwin (osx)

### CODE REVIEW

**Comment by chrisamti** [comment]
I think the circleci test is wrong. on a real mac my patch works.

**Comment by chrisamti** [comment]
looking into github.com/shirou/gopsutil/disk/disk_darwin.go:

instead of: 
```
d := PartitionStat{
			Device:     common.IntToString(stat.Mntfromname[:]),
			Mountpoint: common.IntToString(stat.Mntonname[:]),
			Fstype:     common.IntToString(stat.Fstypename[:]),
			Opts:       opts,
		}
```

it should be: 
```
d := PartitionStat{
			Device:     common.IntToString(stat.Mntfromname[:]),
			Mountpoint: common.IntToString(stat.Mntonname[:]),
			Fstype:     common.IntToString(stat.Fstypename[:]),
			Opts:       opts,
}
```

to reflect: 
https://github.com/golang/sys/blob/master/unix/ztypes_darwin_amd64.go
```
type Statfs_t struct {
	Bsize       uint32
	Iosize      int32
	Blocks      uint64
	Bfree       uint64
	Bavail      uint64
	Files       uint64
	Ffree       uint64
	Fsid        Fsid
	Owner       uint32
	Type        uint32
	Flags       uint32
	Fssubtype   uint32
	Fstypename  [16]byte
	Mntonname   [1024]byte
	Mntfromname [1024]byte
	Flags_ext   uint32
	Reserved    [7]uint32
}
```

**Comment by Lomanic** [comment]
Sorry but there was no point of duplicating #956 while not taking into account https://github.com/shirou/gopsutil/pull/956#issuecomment-705683928 and even adding an empty line. As I didn't have time before, I was hoping @tmm1 would update Gopkg.lock in his PR. Opened and merged #970 where the tests were running successfully, thanks to the updated Gopkg.lock.

**Comment by chrisamti** [comment]
> Sorry but there was no point of duplicating #956 while not taking into account [#956 (comment)](https://github.com/shirou/gopsutil/pull/956#issuecomment-705683928) and even adding an empty line. As I didn't have time before, I was hoping @tmm1 would update Gopkg.lock in his PR. Opened and merged #970 where the tests were running successfully, thanks to the updated Gopkg.lock.

Sure. Thx for fixing.

**Pull request closed without merging**
