### PR TITLE
get IOCounters for aix with perfstat

### PR DESCRIPTION
**Pull request by chbuescher**
get net interface statistics for aix from perfstat without calling netstat and parsing the output

### CODE REVIEW

**Comment by shirou** [comment]
Thank you for the PR. However, [perfstat](https://github.com/power-devops/perfstat) looks using CGO. We would like to implement as much as possible in Pure Go. Are there any obvious advantages over the current implementation?

**Comment by Lomanic** [comment]
We could have two files `net/net_aix_cgo.go` `net/net_aix_nocgo.go` redefining IOCountersWithContext according to build flags like on some other OSes, that would be preferable.

**Comment by chbuescher** [comment]
I see the point using pure go, especially for cross compilation.
But using the perfstat calls should improve memory & cpu usage and make it more robust.
(language settings, changes of cli tools options or output format ..)
Btw, the aix cpu, load, disk & net implementations already are using perfstat

**Comment by shirou** [comment]
Ah, sorry I forget perfstat is already added. So could you split into `net/net_aix_cgo.go` and `net/net_aix_nocgo.go` as @Lomanic said? (and also rebase to fix lint error)

**Comment by chbuescher** [comment]
uh, magic, i thought i had to create a new pull request but it seems github did the merge for me.

**Review by shirou — APPROVED** [review]
Thank you for updating and great contribution!

**Pull request merged**
