### PR TITLE
replace self/mounts with self/mountinfo

### PR DESCRIPTION
**Pull request by nvinzens**
We had an internal problem where on of our device names would get reported as `/dev/root` instead of its real name `vda5`.
We were able to resolve that problem by reading the `/self/proc/mountinfo` file instead of `/self/proc/mounts`. `mountinfo` contains all the same data as `mounts`plus some additional fields like the devices major/minor number, which allows us to find `/dev/root`s real name by reading `/sys/dev/block/`.
More information about `mountinfo`can be found [here](http://man7.org/linux/man-pages/man5/proc.5.html).

### CODE REVIEW

**Comment by Lomanic** [comment]
Tested OK on Debian 9 that it still works the same, but I'm curious about a reproduction case, what was the result of the `mount` command in this case?

**Comment by nvinzens** [comment]
Sure, heres the output from `mount` and whats stored in `/proc/self/mounts`/ `/proc/self/mountinfo` (I changed the server name and removed one entry because of privacy reasons)
```
[server:~]# mount
/dev/vda5 on / type ext4 (rw,noatime,barrier=1)
proc on /proc type proc (rw,nosuid,noexec,nodev,hidepid=0,gid=0)
sysfs on /sys type sysfs (rw,nosuid,noexec,nodev)
none on /run type tmpfs (rw,nosuid,noexec,mode=0755,size=20%)
/dev/vda2 on /boot type ext3 (ro,noatime,barrier=1)
/dev/vda6 on /usr/backup type ext4 (rw,noatime,nosuid,nodev,barrier=1)
/dev/vda7 on /shared type ext3 (rw,noatime,nodev,barrier=1)
none on /dev/pts type devpts (rw,noexec,nosuid,gid=7,mode=0620)
none on /tmp type tmpfs (rw,noatime,nosuid,noexec,nodev,size=40%)
none on /var/tmp type tmpfs (rw,noatime,nosuid,noexec,nodev,size=40%)
shm on /dev/shm type tmpfs (rw)
````
```
[server:~]# cat /proc/self/mounts
/dev/root / ext4 rw,noatime,data=ordered 0 0
devtmpfs /dev devtmpfs rw,relatime,size=2022060k,nr_inodes=505515,mode=755 0 0
none /run tmpfs rw,nosuid,noexec,relatime,size=809544k,mode=755 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
/dev/vda2 /boot ext3 ro,noatime,errors=continue,user_xattr,acl,barrier=1,data=writeback 0 0
/dev/vda6 /usr/backup ext4 rw,nosuid,nodev,noatime,data=ordered 0 0
/dev/vda7 /shared ext3 rw,nodev,noatime,errors=continue,user_xattr,acl,barrier=1,data=writeback 0 0
none /dev/pts devpts rw,nosuid,noexec,relatime,gid=7,mode=620 0 0
none /tmp tmpfs rw,nosuid,nodev,noexec,noatime,size=1619084k 0 0
none /var/tmp tmpfs rw,nosuid,nodev,noexec,noatime,size=1619084k 0 0
shm /dev/shm tmpfs rw,relatime 0 0
```
```
[server:~]# cat /proc/self/mountinfo
17 0 253:5 / / rw,noatime - ext4 /dev/root rw,data=ordered
18 17 0:6 / /dev rw,relatime - devtmpfs devtmpfs rw,size=2022060k,nr_inodes=505515,mode=755
19 17 0:17 / /run rw,nosuid,noexec,relatime - tmpfs none rw,size=809544k,mode=755
20 17 0:4 / /proc rw,nosuid,nodev,noexec,relatime - proc proc rw
21 17 0:18 / /sys rw,nosuid,nodev,noexec,relatime - sysfs sysfs rw
22 17 253:2 / /boot ro,noatime - ext3 /dev/vda2 ro,errors=continue,user_xattr,acl,barrier=1,data=writeback
23 17 253:6 / /usr/backup rw,nosuid,nodev,noatime - ext4 /dev/vda6 rw,data=ordered
24 17 253:7 / /shared rw,nodev,noatime - ext3 /dev/vda7 rw,errors=continue,user_xattr,acl,barrier=1,data=writeback
25 18 0:13 / /dev/pts rw,nosuid,noexec,relatime - devpts none rw,gid=7,mode=620
26 17 0:19 / /tmp rw,nosuid,nodev,noexec,noatime - tmpfs none rw,size=1619084k
27 17 0:20 / /var/tmp rw,nosuid,nodev,noexec,noatime - tmpfs none rw,size=1619084k
28 18 0:21 / /dev/shm rw,relatime - tmpfs shm rw
```

**Comment by shirou** [comment]
Sorry for late response. Your PR changes more stable and after switching using mountinfo, we can have a room for extend. 

However, because of late, it is conflicted. Could you resolve this? after that, I will merge. Thank you for your contribution!

**Comment by shirou** [comment]
Thank you!!

**Pull request merged**
