### PR TITLE
[net] Implements windows net package Connections and ConnectionsPid

### PR DESCRIPTION
**Pull request by pytimer**
Sorry, i am busy in recent days.

Implement #534 . Support for Windows net package, i implements Connections() and ConnectionsPid() two functions.

Usage is similar with linux net:

```go
package main

import (
	"fmt"

	"github.com/shirou/gopsutil/net"
)

func main() {
	fmt.Println(net.Connections("tcp"))
	fmt.Println(net.ConnectionsPid("tcp4", 8092))
}
```

I don't know other functions how to implement, if anyone have idea, welcome to tell me. Thanks.

### CODE REVIEW

**Comment by Lomanic** [comment]
Thanks for this great PR @pytimer.

I won't be able to test this before the weekend, but just reading the code:

- `types_platform.go` files are used for cgo/go-tool -godefs, you should merge `types_windows.go ` inside `net_windows.go`
- merge `net_windows_dll.go` inside `net_windows.go`, it would be the only file with this name (pkg_platform_dll.go) otherwise 
- don't export new functions only defined on a given platform (Windows) and not in the other ones ([GetExtendedTcpTable](https://github.com/shirou/gopsutil/pull/549/files#diff-19e956a21fb8ae72228e1f6533375bf7R241), [GetExtendedUdpTable](https://github.com/shirou/gopsutil/pull/549/files#diff-19e956a21fb8ae72228e1f6533375bf7R249))
- [TCPStatuses](https://github.com/shirou/gopsutil/pull/549/files#diff-19e956a21fb8ae72228e1f6533375bf7R226) is not defined the same way than in Linux (different types even), hence I think 3rd-party code using this variable would not be not portable between these platforms.

**Comment by pytimer** [comment]
Thanks for your reply.

I think i should do at least two things, as follows:

- merge `net_windows_dll.go` and `types_windows.go` inside `net_windows.go`, but i am afried to this file line will long. 

- update functions not exposed.

i don't understand TCPStatuses, can you explain it again? thanks.

**Comment by pytimer** [comment]
@Lomanic i merge `net_windows_dll.go` and `types_windows.go` inside `net_windows.go`, i update TCPStatuses to [tcpStatuses](https://github.com/shirou/gopsutil/pull/549/files#diff-19e956a21fb8ae72228e1f6533375bf7R226).

I don't know i understand right? If it wrong, welcome to point out. Thanks.

**Comment by Lomanic** [comment]
TCPStatuses is already defined on Linux in the same package with an incompatible type [here](https://github.com/shirou/gopsutil/blob/8563278a9de317ae1ce9affdf6715ce7aee5bba9/net/net_linux.go#L236), this is what I'm talking about. @shirou implemented this in https://github.com/shirou/gopsutil/commit/32c62b5d484e1ffc94aa97ed4de2642d9ace5872 so he is the most knowledgeable about that and about interoperability between these platforms.

**Comment by pytimer** [comment]
I think can we  move common variable to `net.go`? like kindTCP4, etc.. 

Windows net status is different from linux, so i defined new variable.This variable now is private, and itonly used in net package, not used by 3rd-party code.

is it deal right?

**Comment by shirou** [comment]
Thank you for your very cool contribution! 

`TCPStatuses` is used to parse TCP status for linux `proc` only. So we don't need to use for other platforms. (It is exported but when I wrote this, I didn't understand well the exposure is important)

**Comment by pytimer** [comment]
I already change net_windows.go `TCPStatuses` to `tcpStatuses`, it used to parse tcp status for windows.

**Comment by Lomanic** [comment]
Don't export the following types/constants and make them Go-compliant (convert ALL_CAPS to mixedCaps, put a comment referencing their proper name in the win32 API docs, check with [golint](//golang.org/x/lint/golint), see also [Effective Go](https://golang.org/doc/effective_go.html#mixed-caps))

* MIB_TCP_STATE
* TCP_TABLE_CLASS
* TCP_TABLE_BASIC_LISTENER
* TCP_TABLE_BASIC_CONNECTIONS
* TCP_TABLE_BASIC_ALL
* TCP_TABLE_OWNER_PID_LISTENER
* TCP_TABLE_OWNER_MODULE_CONNECTIONS
* TCP_TABLE_OWNER_MODULE_ALL
* UDP_TABLE_CLASS
* UDP_TABLE_BASIC
* UDP_TABLE_OWNER_PID
* UDP_TABLE_OWNER_MODULE
* MIB_TCPROW_OWNER_PID
* MIB_TCPTABLE_OWNER_PID
* MIB_TCP6ROW_OWNER_PID
* MIB_TCP6TABLE_OWNER_PID
* PMIB_TCPTABLE_OWNER_PID_ALL
* PMIB_TCP6TABLE_OWNER_PID_ALL
* MIB_UDPROW_OWNER_PID
* MIB_UDPTABLE_OWNER_PID
* MIB_UDP6ROW_OWNER_PID
* MIB_UDP6TABLE_OWNER_PID
* PMIB_UDPTABLE_OWNER_PID
* PMIB_UDP6TABLE_OWNER_PID

Otherwise I tested it on Windows, excellent work @pytimer, it works great!

**Comment by pytimer** [comment]
ok. I will see about you said. Thanks.

**Comment by pytimer** [comment]
@Lomanic  I send a new commit to fix this PR problem, you can check it again.

If something missing, please tell me. Thanks.

**Pull request merged**
