### PR TITLE
Add support for parsing the tgid (thread group id) field.

### PR DESCRIPTION
**Pull request by nkirsch**
Parses the tgid field, which is the thread group id (aka process id) on Linux.

### CODE REVIEW

**Comment by shirou** [comment]
gopsutils is aim to be multi platform library. So adding API only Linux is not welcome. At least windows, freebsd, and darwin should supported. But `NotImplementedYet` is ok.

**Comment by shirou** [comment]
@nkirsch Could you add Windows ?

Below is just a comment for some others.

From  [5.2.2. Linux® processes and thread identifiers](https://www.freebsd.org/doc/en_US.ISO8859-1/articles/linux-emulation/mi.html) , there is not TGID at least FreeBSD. (perhaps, Linux only). So we should decide fake it or leave `NotImplemented` (or close this PR).

According to `5.2.3. PID mangling`, 
- in kernel (in Linuxulator) PID = PID and TGID = shared -> group pid
- to userland we present PID = shared -> group_pid and TID = proc -> p_pid
But we can not change PID meaning in this API version. So I am thinking about return `KInfoProc -> Pgid` as TGID.

**Comment by shirou** [comment]
Thank you for your contribution!

**Comment by nkirsch** [comment]
@shirou My pleasure! Thanks for the wonderful library.

**Pull request merged**
