### PR TITLE
Add pages in/out/fault statistics (as read from vmstat)

### PR DESCRIPTION
**Pull request by lootek**
see: https://superuser.com/questions/785447/what-is-the-exact-difference-between-the-parameters-pgpgin-pswpin-and-pswpou

### CODE REVIEW

**Comment by lootek** [comment]
cc @tomekkolo @adamiklukasz

**Comment by Lomanic** [comment]
I don't have a functional computer at hand right now but this will break the `mem` package tests (`TestSwapMemoryStat_String`), so you should amend your commit to fix them. 

This is also a breaking change in the API (`SwapMemoryStat.Sin` and `SwapMemoryStat.Sout` renamed). This is a small change so I might be personally OK with that.

**Comment by lootek** [comment]
@Lomanic thanks for looking at this PR

1. Added missing tests
2. Reverted name change. Shame on me here - normally I'm super-cautious about _not_ making breaking changes... Here I must have (incorrectly) assumed that I was only changing the internal field, leaving the json tag untouched.

**Comment by shirou** [comment]
Thank you for your contribution! page in/out/fault is good information. and other platform at least FreeBSD has same information, so we can expand to others at another PR.

**Pull request merged**
