### PR TITLE
host: add support for linux/loong64

### PR DESCRIPTION
**Pull request by abner-chenc**
Signed-off-by: Guoqi Chen <chenguoqi@loongson.cn>
Co-authored-by: Jiantao Shan <shanjiantao@loongson.cn>

### CODE REVIEW

**Comment by chenguoqi-cc** [comment]
There is already a pull request for loong64 support, but it has been turned off. see #1080.  by @merore

- loong64 GOARCH value reserved for LoongArch architecture: https://golang.org/doc/go1.17.
- golang issues: https://github.com/golang/go/issues/46229
- golang : https://github.com/loongson/go/tree/loong64-master
- LoongArch documents:https://loongson.github.io/LoongArch-Documentation/LoongArch-Vol1-EN.html
- OS: https://github.com/sunhaiyong1978/CLFS-for-LoongArch/releases/tag/2.3
- kernel: https://github.com/loongson/linux/tree/loongarch-next


go version && go test ./...
```
go version devel go1.18-9dfe8c02b8 Mon Jan 10 21:40:35 2022 +0800 linux/loong64
?       github.com/shirou/gopsutil/v3   [no test files]
ok      github.com/shirou/gopsutil/v3/cpu       0.160s
ok      github.com/shirou/gopsutil/v3/disk      0.010s
ok      github.com/shirou/gopsutil/v3/docker    0.025s
ok      github.com/shirou/gopsutil/v3/host      0.020s
ok      github.com/shirou/gopsutil/v3/internal/common   0.066s
ok      github.com/shirou/gopsutil/v3/load      0.021s
ok      github.com/shirou/gopsutil/v3/mem       0.013s
ok      github.com/shirou/gopsutil/v3/net       0.028s
ok      github.com/shirou/gopsutil/v3/process   2.532s
```

**Comment by shirou** [comment]
go1.19 which supports LoongArch 64-bit has been [released](https://tip.golang.org/doc/go1.19#loong64). I will merge when 1.18 becomes EoL. Otherwise, test will fail.

**Comment by irwinsun** [comment]
> go1.19 which supports LoongArch 64-bit has been [released](https://tip.golang.org/doc/go1.19#loong64). I will merge when 1.18 becomes EoL. Otherwise, test will fail.

too long. . At least 7 months to wait until v1.20 release...

**Comment by yjagdale** [comment]
When we can expect this PR in the master?

**Comment by shirou** [comment]
Since go1.20 has been released, I merge this PR. Thank you for your contribution.

**Pull request merged**
