### PR TITLE
Fix bug for func named ReadLinesOffsetN

### PR DESCRIPTION
**Pull request by 851235550**
Fixes: https://github.com/shirou/gopsutil/issues/1201

### CODE REVIEW

**Review by shirou — APPROVED** [review]
You are truly right! Thank you so much!

**Comment by 851235550** [comment]
> You are truly right! Thank you so much!
> 
> But test is failing?

em, I'm looking at why did the test fail

**Comment by 851235550** [comment]
Hi, @shirou 
I adjusted the code, I believe it should be able to run

**Review by shirou — APPROVED** [review]
LGTM, Thank you for your contribution!

**Pull request merged**
