### PR TITLE
Linux temperature

### PR DESCRIPTION
**Pull request by cshunger**
I made these changes because we were not getting useful output for the current temperature for any core. The output we were receiving was:

```
39 temperatures found:
0 - {"sensorKey":"i350bb","sensorTemperature":49}
1 - {"sensorKey":"i350bb","sensorTemperature":49}
2 - {"sensorKey":"i350bb","sensorTemperature":49}
3 - {"sensorKey":"i350bb","sensorTemperature":49}
4 - {"sensorKey":"coretemp","sensorTemperature":33}
5 - {"sensorKey":"coretemp","sensorTemperature":33}
6 - {"sensorKey":"coretemp","sensorTemperature":33}
7 - {"sensorKey":"coretemp","sensorTemperature":33}
8 - {"sensorKey":"coretemp","sensorTemperature":33}
9 - {"sensorKey":"coretemp","sensorTemperature":24}
10 - {"sensorKey":"coretemp","sensorTemperature":24}
11 - {"sensorKey":"coretemp","sensorTemperature":24}
12 - {"sensorKey":"coretemp","sensorTemperature":24}
13 - {"sensorKey":"coretemp","sensorTemperature":24}
14 - {"sensorKey":"coretemp","sensorTemperature":22}
15 - {"sensorKey":"coretemp","sensorTemperature":22}
16 - {"sensorKey":"coretemp","sensorTemperature":22}
17 - {"sensorKey":"coretemp","sensorTemperature":22}
18 - {"sensorKey":"coretemp","sensorTemperature":22}
19 - {"sensorKey":"coretemp","sensorTemperature":27}
20 - {"sensorKey":"coretemp","sensorTemperature":27}
21 - {"sensorKey":"coretemp","sensorTemperature":27}
22 - {"sensorKey":"coretemp","sensorTemperature":27}
23 - {"sensorKey":"coretemp","sensorTemperature":27}
24 - {"sensorKey":"coretemp","sensorTemperature":23}
25 - {"sensorKey":"coretemp","sensorTemperature":23}
26 - {"sensorKey":"coretemp","sensorTemperature":23}
27 - {"sensorKey":"coretemp","sensorTemperature":23}
28 - {"sensorKey":"coretemp","sensorTemperature":23}
29 - {"sensorKey":"coretemp","sensorTemperature":33}
30 - {"sensorKey":"coretemp","sensorTemperature":33}
31 - {"sensorKey":"coretemp","sensorTemperature":33}
32 - {"sensorKey":"coretemp","sensorTemperature":33}
33 - {"sensorKey":"coretemp","sensorTemperature":33}
34 - {"sensorKey":"coretemp","sensorTemperature":31}
35 - {"sensorKey":"coretemp","sensorTemperature":31}
36 - {"sensorKey":"coretemp","sensorTemperature":31}
37 - {"sensorKey":"coretemp","sensorTemperature":31}
38 - {"sensorKey":"coretemp","sensorTemperature":31}
```

The output with the following code changes is now:
```
31 temperatures found
0 - {"SensorKey":"i350bb_loc1_crit", "sensorTemperature": "110"}
1 - {"SensorKey":"i350bb_loc1_input", "sensorTemperature": "48"}
2 - {"SensorKey":"i350bb_loc1_max", "sensorTemperature": "120"}
3 - {"SensorKey":"coretemp_physicalid0_crit", "sensorTemperature": "84"}
4 - {"SensorKey":"coretemp_physicalid0_critalarm", "sensorTemperature": "0"}
5 - {"SensorKey":"coretemp_physicalid0_input", "sensorTemperature": "33"}
6 - {"SensorKey":"coretemp_physicalid0_max", "sensorTemperature": "74"}
7 - {"SensorKey":"coretemp_core0_crit", "sensorTemperature": "84"}
8 - {"SensorKey":"coretemp_core0_critalarm", "sensorTemperature": "0"}
9 - {"SensorKey":"coretemp_core0_input", "sensorTemperature": "26"}
10 - {"SensorKey":"coretemp_core0_max", "sensorTemperature": "74"}
11 - {"SensorKey":"coretemp_core1_crit", "sensorTemperature": "84"}
12 - {"SensorKey":"coretemp_core1_critalarm", "sensorTemperature": "0"}
13 - {"SensorKey":"coretemp_core1_input", "sensorTemperature": "22"}
14 - {"SensorKey":"coretemp_core1_max", "sensorTemperature": "74"}
15 - {"SensorKey":"coretemp_core2_crit", "sensorTemperature": "84"}
16 - {"SensorKey":"coretemp_core2_critalarm", "sensorTemperature": "0"}
17 - {"SensorKey":"coretemp_core2_input", "sensorTemperature": "27"}
18 - {"SensorKey":"coretemp_core2_max", "sensorTemperature": "74"}
19 - {"SensorKey":"coretemp_core3_crit", "sensorTemperature": "84"}
20 - {"SensorKey":"coretemp_core3_critalarm", "sensorTemperature": "0"}
21 - {"SensorKey":"coretemp_core3_input", "sensorTemperature": "23"}
22 - {"SensorKey":"coretemp_core3_max", "sensorTemperature": "74"}
23 - {"SensorKey":"coretemp_core4_crit", "sensorTemperature": "84"}
24 - {"SensorKey":"coretemp_core4_critalarm", "sensorTemperature": "0"}
25 - {"SensorKey":"coretemp_core4_input", "sensorTemperature": "33"}
26 - {"SensorKey":"coretemp_core4_max", "sensorTemperature": "74"}
27 - {"SensorKey":"coretemp_core5_crit", "sensorTemperature": "84"}
28 - {"SensorKey":"coretemp_core5_critalarm", "sensorTemperature": "0"}
29 - {"SensorKey":"coretemp_core5_input", "sensorTemperature": "31"}
30 - {"SensorKey":"coretemp_core5_max", "sensorTemperature": "74"}
```

The reason for the drop in returned temperatures is because you were creating a temperature reading for every `temp*_*` file but `temp*_label` does not return a temperature, it returns a label to this temperature.

### CODE REVIEW

**Comment by cshunger** [comment]
@shirou this now is also a closer match to the `psutil` output for temperature which is:

```
In [2]: psutil.sensors_temperatures()
Out[2]: 
{'coretemp': [shwtemp(label='Physical id 0', current=34.0, high=80.0, critical=98.0),
  shwtemp(label='Core 0', current=31.0, high=80.0, critical=98.0),
  shwtemp(label='Core 1', current=34.0, high=80.0, critical=98.0),
  shwtemp(label='Core 2', current=33.0, high=80.0, critical=98.0),
  shwtemp(label='Core 3', current=32.0, high=80.0, critical=98.0)]}
```

**Comment by shirou** [comment]
Thank you for your contribution!

I don't have such a server, so I can not confirm. But it looks better output.
So I will merge this PR after a few days. If anyone have something, please let us know.

**Comment by cshunger** [comment]
@shirou I tested on 
`3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 GNU/Linux`

The output [above](https://github.com/shirou/gopsutil/pull/485#issue-292132753) is from testing on Debian.

**Comment by cshunger** [comment]
@shirou if no one comments on this today could we merge this PR? My team is trying to get temperature recording in by Wednesday.

**Comment by shirou** [comment]
If someone have some troubles, please comments here or make a new Issue. Thank you for your contribution!.

**Pull request merged**
