### PR TITLE
prevent hang on pkg import if wmi.Query hangs

### PR DESCRIPTION
**Pull request by leafnunes**
This is to address #451

### CODE REVIEW

**Comment by shirou** [comment]
Could you dig more deeper why it hangs? It happens on other Windows environment?

And, I agree to add a timeout feature. But recent golang has `context` library which has [timeout](https://golang.org/pkg/context/#WithTimeout). Could you change to use `context` with some small wrap function?

**Comment by leafnunes** [comment]
My access to windows instances is relatively limited, especially older platforms. Downstream users have observed this on windows server 2008 and 2012, but not 2016. If i can get ahold of decent debugging tools and regular access to a susceptible image, i can do more debugging.

Before i do the change, let me make sure i understand what you want: would you prefer i wrap every wmi.Query call with a context with timeouts, or just the one i'm wrapping now? Is using `common.Timeout` as the default for all of them ok with you?

**Comment by shirou** [comment]
Could you create a wrapper function in `internal/common/common_windows.go`.
The wrapper function is like this.
```
func WMIQueryWithContext(ctx context.Context, query string, dst interface{}, connectServerArgs ...interface{}) error {
	errChan := make(chan error, 1)
	go func() {
		errChan <- wmi.Query(query, dst, connectServerArgs)
	}()

	select {
	case <-ctx.Done():
		return ctx.Err()
	case err := <-errChan:
		return err
	}
}
```

Then, we can use like this
```
	ctx, cancel := context.WithTimeout(context.Background(), common.Timeout)
	defer cancel()
	if err := WMIQueryWithContext(ctx, q, ret); err != nil{
		return err
	}
```

using `common.Timeout` is fine. and I will appreciate if you change all functions which use `wmi.Query`, but only `cpu.PerfInfo()` is too enough.

**Comment by leafnunes** [comment]
How's this look?

**Comment by shirou** [comment]
perfect!! Thank you for your contribution!!

**Pull request merged**
