### PR TITLE
Allow gopsutil docker to build on non-linux boxes by stubbing out non…

### PR DESCRIPTION
**Pull request by sparrc**
…-linux libraries

### CODE REVIEW

**Comment by sparrc** [comment]
This should allow gopsutil/docker to build on mac systems, but will currently return a NotImplementedError if the functions are actually tried to use. Mac machines will still have access the the datatypes of the docker package though.

**Comment by shirou** [comment]
docker package is separated from other packages. So I was thinking just not import docker package on on non-linux system.
This PR means you want to use docker package with linux AND non-linux system from one source code, and also want to use datatypes in the docker package.

I think your PR is quite reasonable and will merge with thankfulness, but just want a clarification.

Thank you.

**Comment by sparrc** [comment]
@shirou, the reason for wanting this was that we would like to not have to write separate build files for the docker monitoring system on our end for linux & mac. Instead, we would like to be able to build and unit test the docker system on both OSes.

One of the main benefits of this PR is that it allows a mac system to access all the datatypes of the docker package for the purpose of unit testing, so that we can build on a mac despite the functions not being implemented.

**Comment by shirou** [comment]
I understand. Thank you!

I am interested in docker monitoring system, but the docker package is not currently well tested on various environment. I will appreciate if you find and report a bug.

**Pull request merged**
