### PR TITLE
Return a valid JSON `String()` output for network lists

### PR DESCRIPTION
**Pull request by moul**
Hi, what do you think about JSON marshalling lists as you are already doing with standalone items ?

If you like the idea, I can continue on the other resource types

---

Before

``` go
fmt.Println(myList)
// output: [{"a": "hello", "c": 42} {"a": "world", "c": 1337}] -> invalid json
```

After

``` go
fmt.Println(myList)
// output: [{"a": "hello", "c": 42},{"a": "world", "c": 1337}] -> valid json
```

### CODE REVIEW

**Comment by QuentinPerez** [comment]
LGTM

**Comment by shirou** [comment]
Sorry, could you tell me more detail about what is a problem?

```
	V := InterfaceStat{
		MTU:  1500,
		Name: "eth0",
		Addrs: []InterfaceAddr{
			{Addr: "1.2.3.4"}, {Addr: "5.6.7.8"},
		},
	}
        fmt.Println(V)
```

returns `{"mtu":1500,"name":"eth0","hardwareaddr":"","flags":null,"addrs":[{"addr":"1.2.3.4"},{"addr":"5.6.7.8"}]}` and it is valid.

**Comment by moul** [comment]
Your example is correct, it works perfectly for standalone items, but JSON is invalid as soon as you print a list (space separator instead of comma)

**Comment by shirou** [comment]
I got it. You want to use `InterfaceStat.Addrs` individually. Thank you for teach me.

If you make types for other items, I will appreciate and merge it.

**Comment by moul** [comment]
Perfect :)

**Comment by shirou** [comment]
Sorry for the very long time wait. fixed by #938.

**Pull request closed without merging**
