### PR TITLE
add Uids field to net_linux

### PR DESCRIPTION
**Pull request by jkahrs**

### CODE REVIEW

**Comment by jkahrs** [comment]
while looking at it i'm not sure if i'm happy about cluttering this up so much :/

**Comment by shirou** [comment]
Thank you so much!
But I feel copy everything from process_linux is a little bit messy. Could you copy (or write)  only the uid related things?

**Comment by jkahrs** [comment]
Thank you for your feedback @shirou.
I'll look into this a little bit later this week. I think I'll be able to clean out some unnessary code.

**Comment by shirou** [comment]
Thank you for your contribution!

**Pull request merged**
