### PR TITLE
fix: read temperature sensors darwin arm

### LINKED ISSUE #1332: SensorsTemperatures returns 0 values for all sensors on darwin arm64 (M1)
**Describe the bug**
the temperature value of each TemperatureStat object in the array returned by host.SensorsTemperatures() is 0 on an M1.

**To Reproduce**
```go
package main

import (
	"encoding/json"
	"fmt"
	"github.com/shirou/gopsutil/v3/host"
)

func main() {
	tstat, _ := host.SensorsTemperatures()
	serialized, _ := json.Marshal(tstat)
	fmt.Printf("%s", string(serialized))
}
```

Here's the output:
```
[
  {
    "sensorKey": "TA0P",
    "temperature": 0,
    "sensorHigh": 0,
    "sensorCritical": 0
  },
  {
    "sensorKey": "TA1P",
    "temperature": 0,
    "sensorHigh": 0,
    "sensorCritical": 0
  },
  {
    "sensorKey": "TC0D",
    "temperature": 0,
    "sensorHigh": 0,
    "sensorCritical": 0
  },
  {
    "sensorKey": "TC0H",
    "temperature": 0,
    "sensorHigh": 0,
    "sensorCritical": 0
  },
  {
    "sensorKey": "TC0P",
    "temperature": 0,
    "sensorHigh": 0,
    "sensorCritical": 0
  },
  {
    "sensorKey": "TB0T",
    "temperature": 0,
    "sensorHigh": 0,
    "sensorCritical": 0
  },
  {
    "sensorKey": "TB1T",
    "temperature": 0,
    "sensorHigh": 0,
    "sensorCritical": 0
  },
  {
    "sensorKey": "TB2T",
    "temperature": 0,
    "sensorHigh": 0,
    "sensorCritical": 0
  },
  {
    "sensorKey": "TB3T",
    "temperature": 0,
    "sensorHigh": 0,
    "sensorCritical": 0
  },
  {
    "sensorKey": "TG0D",
    "temperature": 0,
    "sensorHigh": 0,
    "sensorCritical": 0
  },
  {
    "sensorKey": "TG0H",
    "temperature": 0,
    "sensorHigh": 0,
    "sensorCritical": 0
  },
  {
    "sensorKey": "TG0P",
    "temperature": 0,
    "sensorHigh": 0,
    "sensorCritical": 0
  },
  {
    "sensorKey": "TH0P",
    "temperature": 0,
    "sensorHigh": 0,
    "sensorCritical": 0
  },
  {
    "sensorKey": "TM0S",
    "temperature": 0,
    "sensorHigh": 0,
    "sensorCritical": 0
  },
  {
    "sensorKey": "TM0P",
    "temperature": 0,
    "sensorHigh": 0,
    "sensorCritical": 0
  },
  {
    "sensorKey": "TN0H",
    "temperature": 0,
    "sensorHigh": 0,
    "sensorCritical": 0
  },
  {
    "sensorKey": "TN0D",
    "temperature": 0,
    "sensorHigh": 0,
    "sensorCritical": 0
  },
  {
    "sensorKey": "TN0P",
    "temperature": 0,
    "sensorHigh": 0,
    "sensorCritical": 0
  },
  {
    "sensorKey": "TI0P",
    "temperature": 0,
    "sensorHigh": 0,
    "sensorCritical": 0
  },
  {
    "sensorKey": "TI1P",
    "temperature": 0,
    "sensorHigh": 0,
    "sensorCritical": 0
  },
  {
    "sensorKey": "TW0P",
    "temperature": 0,
    "sensorHigh": 0,
    "sensorCritical": 0
  }
]
```

**Expected behavior**
Return valid temperature sensor data for one or more of the sensors.

**Environment (please complete the following information):**

$ sw_vers
ProductName:	macOS
ProductVersion:	12.4
BuildVersion:	21F79

$ uname -a
Darwin xxxx 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

**Additional context**

go version go1.18 darwin/arm64

In contrast, here's the output from the same program built and executed on a darwin x86_64 host:

```
[
    {
        "sensorKey": "TA0P",
        "temperature": 0,
        "sensorHigh": 0,
        "sensorCritical": 0
    },
    {
        "sensorKey": "TA1P",
        "temperature": 0,
        "sensorHigh": 0,
        "sensorCritical": 0
    },
    {
        "sensorKey": "TC0D",
        "temperature": 0,
        "sensorHigh": 0,
        "sensorCritical": 0
    },
    {
        "sensorKey": "TC0H",
        "temperature": 0,
        "sensorHigh": 0,
        "sensorCritical": 0
    },
    {
        "sensorKey": "TC0P",
        "temperature": 31,
        "sensorHigh": 0,
        "sensorCritical": 0
    },
    {
        "sensorKey": "TB0T",
        "temperature": 0,
        "sensorHigh": 0,
        "sensorCritical": 0
    },
    {
        "sensorKey": "TB1T",
        "temperature": 0,
        "sensorHigh": 0,
        "sensorCritical": 0
    },
    {
        "sensorKey": "TB2T",
        "temperature": 0,
        "sensorHigh": 0,
        "sensorCritical": 0
    },
    {
        "sensorKey": "TB3T",
        "temperature": 0,
        "sensorHigh": 0,
        "sensorCritical": 0
    },
    {
        "sensorKey": "TG0D",
        "temperature": 0,
        "sensorHigh": 0,
        "sensorCritical": 0
    },
    {
        "sensorKey": "TG0H",
        "temperature": 0,
        "sensorHigh": 0,
        "sensorCritical": 0
    },
    {
        "sensorKey": "TG0P",
        "temperature": 0,
        "sensorHigh": 0,
        "sensorCritical": 0
    },
    {
        "sensorKey": "TH0P",
        "temperature": 0,
        "sensorHigh": 0,
        "sensorCritical": 0
    },
    {
        "sensorKey": "TM0S",
        "temperature": 0,
        "sensorHigh": 0,
        "sensorCritical": 0
    },
    {
        "sensorKey": "TM0P",
        "temperature": 30,
        "sensorHigh": 0,
        "sensorCritical": 0
    },
    {
        "sensorKey": "TN0H",
        "temperature": 0,
        "sensorHigh": 0,
        "sensorCritical": 0
    },
    {
        "sensorKey": "TN0D",
        "temperature": 0,
        "sensorHigh": 0,
        "sensorCritical": 0
    },
    {
        "sensorKey": "TN0P",
        "temperature": 0,
        "sensorHigh": 0,
        "sensorCritical": 0
    },
    {
        "sensorKey": "TI0P",
        "temperature": 0,
        "sensorHigh": 0,
        "sensorCritical": 0
    },
    {
        "sensorKey": "TI1P",
        "temperature": 0,
        "sensorHigh": 0,
        "sensorCritical": 0
    },
    {
        "sensorKey": "TW0P",
        "temperature": 31,
        "sensorHigh": 0,
        "sensorCritical": 0
    }
]
```

### PR DESCRIPTION
**Pull request by Girbons**
## Description

proposal to read temperature sensors for mac with apple silicon 

fixes #1332 

Tested with M1
image

### CODE REVIEW

**Comment by shirou** [comment]
Thank you for your contribution! At first glance, it looks good. However, I don't have an environment to test it, so could someone else please verify its functionality?

And also, `sensors/darwin_arm_sensors.h` is copied from other project. It is BSD-3 clause license, so it is not a problem, but could you add those two lines on head of the file in order to make it machine readable?

```
// SPDX-FileCopyrightText: Copyright (c) 2016-2018, "freedom" Koan-Sin Tan
// SPDX-License-Identifier: BSD-3-Clause
```

**Comment by Girbons** [comment]
> And also, `sensors/darwin_arm_sensors.h` is copied from other project. It is BSD-3 clause license, so it is not a problem, but could you add those two lines on head of the file in order to make it machine readable?

Sure!

**Comment by davidnewhall** [comment]
Can confirm adding this line to go.mod (and running `go mod tidy`) gives me temperates on an M2 Mac mini that I did not have before.
```
replace github.com/shirou/gopsutil/v4 => github.com/Girbons/gopsutil/v4 ba82fef
```
Screenshot 2024-07-10 at 3 14 10 PM

**Comment by davidnewhall** [comment]
@shirou Can we get this merged? I'd like to release a new version of my app, but not with a replace line in the go mod. I'm happy to pin to the `master` branch on your repo though until there's a new release.

Thanks!

**Review by shirou — APPROVED** [review]
Great job! Thank you for your contribution!

And @davidnewhall, your assistance with the confirmation was very helpful. Thank you so much

**Pull request merged**
