### PR TITLE
Read disk partitions on linux from /proc/mounts instead of /etc/mtab

### LINKED ISSUE #371: disk.Partitions fails on Android
`/etc/mtab` is not available on Android, however `/proc/mounts` is available.

### PR DESCRIPTION
**Pull request by tmm1**
fixes #371

### CODE REVIEW

**Comment by tmm1** [comment]
I tested this on GOOS=android and it works now.

**Comment by shirou** [comment]
After reading some articles, I understand you are correct. Thank you.
- https://linux.die.net/man/8/mount
- http://fibrevillage.com/sysadmin/278-understanding-the-difference-between-etc-mtab-and-proc-mounts-on-linux
- http://www.linuxquestions.org/questions/slackware-14/etc-mtab-vs-proc-self-mounts-371224/

But, `/proc/mounts` is an alias of `/proc/self/mounts` on my linux.

```
lrwxrwxrwx 1 root root 11  5月 19 12:06 /proc/mounts -> self/mounts
```

How about to change `common.HostProc("self/mounts")` ? 

And, if you can run on `GOOS=android`, could we add build tag to `disk_linux.go`? 

`// +build linux, android`

(I think this should not be included in this PR)

**Comment by tmm1** [comment]
Sure, self/mounts works too.

Extra build flag is not required, because GOOS=android automatically sets Linux build flag already.

**Comment by shirou** [comment]
So, could you change to `self/mounts` ? Then, I will merge this PR.

> Extra build flag is not required, because GOOS=android automatically sets Linux build flag already.

Great!

**Comment by tmm1** [comment]
Done!

**Comment by shirou** [comment]
merged. Thank you for your contribution!!

**Pull request merged**
